# config/packages/knp_paginator.yaml
knp_paginator:
    page_range: 5 # Nombre de pages à afficher dans la pagination
    default_options:
        page_name: page # Nom du paramètre pour la page
        sort_field_name: sort # Nom du paramètre pour le champ de tri
        sort_direction_name: direction # Nom du paramètre pour la direction de tri
        distinct: true # Option de suppression des doublons
    template:
        pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig' # Modèle de pagination
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # Modèle pour les liens triables
