security:
  # Configuration des hashers de mot de passe
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  # Configuration des providers
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  # Configuration des firewalls
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: app_user_provider
      form_login:
        login_path: app_login
        check_path: app_login
        enable_csrf: true
      logout:
        path: app_logout
        target: /login # Redirection après déconnexion
      remember_me:
        secret: "%kernel.secret"
        lifetime: 604800

  # Contrôle d'accès basé sur les rôles
  access_control:
    # Chemin réservé aux administrateurs
    - { path: ^/admin, roles: ROLE_ADMIN }
    
    # Chemin réservé aux boutiquiers
    - { path: ^/boutiquier, roles: ROLE_BOUTIQUIER }
    # Chemin réservé aux clients
    - { path: ^/client, roles: [ROLE_BOUTIQUIER, ROLE_CLIENT] }
    - { path: ^/dette, roles: [ROLE_BOUTIQUIER, ROLE_ADMIN,ROLE_CLIENT] }
    
    - { path: ^/client/\d+/ajouter-dette, roles: ROLE_BOUTIQUIER } # Exemple de rôle autorisé
    

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10
